name: 🤖 Android Builds
on: [push, pull_request]

# Global Settings
env:
  # Only used for the cache key. Increment version to force clean build.
  GODOT_BASE_BRANCH: master
  SCONSFLAGS: verbose=yes warnings=extra werror=yes debug_symbols=no module_text_server_fb_enabled=yes

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  android-compile-export:
    name: Compile Android Export
    runs-on: "ubuntu-20.04"
    strategy:
      matrix:
        arch: [armv7, arm64v8, x86, x86_64]
        target: [release, debug]
    steps:
      - uses: actions/checkout@v2

      # Azure repositories are not reliable, we need to prevent azure giving us packages.
      - name: Make apt sources.list use the default Ubuntu repositories
        run: |
          sudo rm -f /etc/apt/sources.list.d/*
          sudo cp -f misc/ci/sources.list /etc/apt/sources.list
          sudo apt-get update

      - name: Set up Java 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} android_arch=${{ matrix.arch }}
          platform: android
          target: ${{ matrix.target }}
          tools: false
          tests: false

  android-template:
    name: Godot templates
    runs-on: "ubuntu-20.04"
    needs: android-compile-export
    steps:
      - uses: actions/checkout@v2

      - name: Generate Godot templates
        run: |
          cd platform/android/java
          ./gradlew generateGodotTemplates
          cd ../../..
          ls -l bin/

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
